import * as vscode from 'vscode';
import axios from 'axios';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.executeSqlQuery', async () => {

        const editor = vscode.window.activeTextEditor;
        if (!editor) {
            vscode.window.showErrorMessage('No active text editor');
            return;
        }

        const selection = editor.selection;
        const text = editor.document.getText(selection).replace(/\r\n|\r|\n/g, ' ');

        if (!text) {
            vscode.window.showErrorMessage('No text selected');
            return;
        }

        const config = vscode.workspace.getConfiguration('sqlQueryExecutor');
        const apiEndpoint = config.get<string>('apiEndpoint');

        try {
            const response = await axios.post(apiEndpoint!, { sql: text }, { headers: { 'Authorization': getToken() } });
            // debugger
            const data = response.data.retorno;

            if (!Array.isArray(data)) {
                throw new Error('Invalid response format');
            }

            // // Create a new document to display the results
            // const document = await vscode.workspace.openTextDocument({
            //     content: createTableView(data),
            //     language: 'markdown'
            // });

            // await vscode.window.showTextDocument(document, { preview: false, viewColumn: vscode.ViewColumn.Beside });

              // Criar um arquivo temporário para o Markdown
            const tempDir = vscode.workspace.workspaceFolders?.[0].uri.fsPath || __dirname;
            const tempFile = path.join(tempDir, 'sql_query_results.md');
            const uri = vscode.Uri.file(tempFile);

            // Escrever o conteúdo Markdown no arquivo
            await vscode.workspace.fs.writeFile(uri, Buffer.from(createTableView(data)));

            // Abrir o arquivo
            // const doc = await vscode.workspace.openTextDocument(uri);
            // await vscode.window.showTextDocument(doc, { preview: false, viewColumn: vscode.ViewColumn.Beside });

            // Abrir a visualização do Markdown Preview Enhanced
            await vscode.commands.executeCommand('markdown-preview-enhanced.openPreview', uri);
        } catch (error) {
            vscode.window.showErrorMessage(`Error executing query: ${error}`);
        }
    });

    context.subscriptions.push(disposable);
}

function createTableView(data: any[]): string {
    if (data.length === 0) return 'No data returned';

    const headers = Object.keys(data[0]);
    let table = '# SQL Query Results\n\n';
    table += '| ' + headers.join(' | ') + ' |\n';
    table += '| ' + headers.map(() => ':---:').join(' | ') + ' |\n';

    data.forEach(row => {
        table += '| ' + headers.map(header => row[header] || '').join(' | ') + ' |\n';
    });

    // Adicionar informações extras
    table += '\n\n*Query executed at: ' + new Date().toLocaleString() + '*\n';
    table += '\n---\n';
    table += 'Generated by SQL Query Executor Extension';

    return table;
}
const getToken = () => "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJRQTdDRmhnblFHbW9HZnlPUnFCX24tT09KVzh5c0tyWGRzbGgxSnpsbG13In0.eyJleHAiOjE3MzE3MDYxOTksImlhdCI6MTczMTcwNTg5OSwiYXV0aF90aW1lIjoxNzMxNzAxMDEyLCJqdGkiOiIyOWIyODI0ZC01ZjhlLTRhMWMtYmRhMC02NTEzMDFmMWIwMjkiLCJpc3MiOiJodHRwczovL2F1dGgtY2l0cy50cnQyMy5qdXMuYnIvYXV0aC9yZWFsbXMvdHJ0LTIzLWRldiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJiMzE5ZWE3Ny0xMDlhLTQ2MGItODM2MS03ZjU2ZjI4MWJlYzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmcm9udC1tYW5hZ2VyIiwic2lkIjoiZjhiNWI4NTctODJlNi00MmFlLTg2NDYtMjNjYmYwZDU4ZjE3IiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNvbGljaXRhbnRlX3RydDIzX2RldiIsImFuYWxpc3RhX3RydDIzX2RldiIsImRlc2Vudm9sdmltZW50b190cnQyM19kZXYiLCJjZW50cmFsZGVzZXJ2aWNvX3RydDIzX2RldiIsImFkbWluX3RydDIzX2RldiIsImdwLWFkbWluIiwiZ2xfYWRtaW4iLCJncC1nZXN0b3ItdXNlciIsImthbmJhbl90cnQyM19kZXYiLCJkZW1vIiwiZGVmYXVsdC1yb2xlcy10cnQtMjMtZGV2IiwiaHlwZXJfYWRtaW4iLCJrYm5fdXNlciIsIm9mZmxpbmVfYWNjZXNzIiwiaHlwX2FkbWluIiwia2JuX2FkbWluIiwidW1hX2F1dGhvcml6YXRpb24iLCJncC11c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaHlwZXJfY2xpZW50IjoiZjA3MjUyYTUtZDgyZi00ZjVhLTg1NWUtZjZlYTU3ZjIyY2FjIiwibmFtZSI6IkJydW5vIEdvbWVzIGRlIE9saXZlaXJhIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYmdvbWVzLm9saXZlaXJhIiwic2Vzc2lvbl90eXBlIjoidW5saW1pdGVkIiwiZ2l2ZW5fbmFtZSI6IkJydW5vIiwiZmFtaWx5X25hbWUiOiJHb21lcyBkZSBPbGl2ZWlyYSIsImVtYWlsIjoiZ29tZXMub2xpdmVpcmFAY2VudHJhbGl0LmNvbS5iciIsImh5cGVyX2NsdXN0ZXJfc3BhY2UiOiI1ODQ5M2NhZS0wY2M0LTQzMjctODU1My1lYWM1YTkwNzFhODYifQ.N81fxFOJPfqo1wLtkAvAJmcQWJ4HBBwxUUwziIhrOk-k6hJDIK476mt3QQ4TKid1oHvh97IdytQg1NRMwftNCiUmsCfa8Vi7eUcUwL0k_9K79YGGpym4QjEpbbr6Y2MagaNEfcQXHxTBDrKdaX9j-UDQNes2TJuZncsm2Y82F9hRkUO7rTiBKx90La9vpqs8MkYthRQD6r6PmktmQCOhqL-td_8aOrfYViTRIVfGKhF63aMbeHJlgP07-OnL8_algPEwc8h2gHPnFs2X84kIpq01AuDthqDH81_i2fwjfYya1dorxVARwWy_Eo1nfjJwVYbpI-ZXO6aer8zR0uSC2g"

export function deactivate() {}

